// Comprehensive DACH-region options for the application form

export const BERUFE: string[] = [
  // IT & Software
  "Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Full-Stack Developer",
  "DevOps Engineer",
  "Cloud Engineer",
  "Data Engineer",
  "Data Scientist",
  "Data Analyst",
  "Machine Learning Engineer",
  "KI-Spezialist/in",
  "IT-Systemadministrator/in",
  "IT-Consultant",
  "IT-Projektmanager/in",
  "Scrum Master",
  "Product Owner",
  "UX/UI Designer/in",
  "Webdesigner/in",
  "Webentwickler/in",
  "Mobile App Developer",
  "QA Engineer / Tester",
  "IT-Sicherheitsspezialist/in",
  "Netzwerktechniker/in",
  "Systemingenieur/in",
  "SAP-Berater/in",
  "Datenbankadministrator/in",
  "IT-Support / Helpdesk",
  "Technical Lead",
  "CTO / IT-Leiter/in",

  // Marketing & Kommunikation
  "Marketing Manager/in",
  "Online Marketing Manager/in",
  "Social Media Manager/in",
  "Content Manager/in",
  "SEO-Spezialist/in",
  "SEA-Manager/in",
  "Performance Marketing Manager/in",
  "Brand Manager/in",
  "Kommunikationsmanager/in",
  "PR-Manager/in",
  "E-Mail Marketing Manager/in",
  "CRM-Manager/in",
  "Copywriter/in",
  "Texter/in",
  "Grafikdesigner/in",
  "Art Director",
  "Creative Director",
  "Event Manager/in",
  "Mediengestalter/in",

  // Vertrieb & Sales
  "Vertriebsmitarbeiter/in",
  "Sales Manager/in",
  "Key Account Manager/in",
  "Business Development Manager/in",
  "Account Manager/in",
  "Vertriebsleiter/in",
  "Inside Sales Manager/in",
  "Außendienstmitarbeiter/in",
  "Verkäufer/in",
  "Einzelhandelskaufmann/-frau",
  "Großhandelskaufmann/-frau",
  "Filialleiter/in",

  // Finanzen & Buchhaltung
  "Buchhalter/in",
  "Bilanzbuchhalter/in",
  "Controller/in",
  "Finanzanalyst/in",
  "Steuerberater/in",
  "Wirtschaftsprüfer/in",
  "Finanzberater/in",
  "Bankkaufmann/-frau",
  "Versicherungskaufmann/-frau",
  "Treasurey Manager/in",
  "Risk Manager/in",
  "Compliance Manager/in",
  "Kreditanalyst/in",
  "Lohnbuchhalter/in",
  "CFO / Finanzleiter/in",

  // Personalwesen / HR
  "HR-Manager/in",
  "Personalreferent/in",
  "Recruiter/in",
  "Talent Acquisition Manager/in",
  "Personalentwickler/in",
  "HR Business Partner",
  "Personalleiter/in",
  "Lohn- und Gehaltsabrechner/in",
  "Employer Branding Manager/in",

  // Verwaltung & Büro
  "Bürokaufmann/-frau",
  "Verwaltungsfachangestellte/r",
  "Assistenz der Geschäftsführung",
  "Sekretär/in",
  "Office Manager/in",
  "Empfangsmitarbeiter/in",
  "Sachbearbeiter/in",
  "Kaufmännische/r Angestellte/r",
  "Teamassistenz",

  // Projektmanagement & Beratung
  "Projektmanager/in",
  "Projektleiter/in",
  "Unternehmensberater/in",
  "Management Consultant",
  "Strategieberater/in",
  "Prozessmanager/in",
  "Change Manager/in",
  "Agile Coach",
  "Programm Manager/in",

  // Ingenieurwesen & Technik
  "Maschinenbauingenieur/in",
  "Elektroingenieur/in",
  "Bauingenieur/in",
  "Wirtschaftsingenieur/in",
  "Verfahrensingenieur/in",
  "Produktionsingenieur/in",
  "Qualitätsingenieur/in",
  "Automatisierungstechniker/in",
  "Mechatroniker/in",
  "Techniker/in",
  "Technische/r Zeichner/in",
  "CAD-Konstrukteur/in",
  "Instandhaltungstechniker/in",
  "Fertigungsleiter/in",
  "Betriebsleiter/in",

  // Gesundheit & Soziales
  "Arzt/Ärztin",
  "Facharzt/Fachärztin",
  "Zahnarzt/Zahnärztin",
  "Apotheker/in",
  "Krankenschwester / Krankenpfleger",
  "Pflegefachkraft",
  "Altenpfleger/in",
  "Physiotherapeut/in",
  "Ergotherapeut/in",
  "Psychologe/Psychologin",
  "Psychotherapeut/in",
  "Sozialarbeiter/in",
  "Sozialpädagoge/in",
  "Erzieher/in",
  "Hebamme",
  "Rettungssanitäter/in",
  "Medizinische/r Fachangestellte/r",
  "Pharmazeutisch-technische/r Assistent/in",
  "Laborant/in",

  // Recht
  "Rechtsanwalt/Rechtsanwältin",
  "Jurist/in",
  "Notar/in",
  "Rechtsanwaltsfachangestellte/r",
  "Compliance Officer",
  "Datenschutzbeauftragte/r",
  "Vertragsmanager/in",

  // Bildung & Wissenschaft
  "Lehrer/in",
  "Professor/in",
  "Dozent/in",
  "Wissenschaftliche/r Mitarbeiter/in",
  "Forscher/in",
  "Trainer/in",
  "Bildungsreferent/in",
  "Schulleiter/in",

  // Logistik & Supply Chain
  "Logistikmanager/in",
  "Supply Chain Manager/in",
  "Lagerist/in",
  "Speditionskaufmann/-frau",
  "Einkäufer/in",
  "Disponent/in",
  "Fuhrparkmanager/in",
  "Zolldeklarant/in",
  "Lagerleiter/in",

  // Handwerk & Produktion
  "Elektriker/in",
  "Schlosser/in",
  "Tischler/in",
  "Installateur/in",
  "Maler/in",
  "Maurer/in",
  "Dachdecker/in",
  "Schweißer/in",
  "CNC-Fräser/in",
  "Industriemechaniker/in",
  "Werkzeugmechaniker/in",
  "Anlagenmechaniker/in",
  "Schreiner/in",
  "Zimmerer/Zimmerin",
  "Bäcker/in",
  "Konditor/in",
  "Koch/Köchin",
  "Fleischer/in",
  "Friseur/in",
  "KFZ-Mechatroniker/in",

  // Gastronomie & Tourismus
  "Hotelfachmann/-frau",
  "Restaurantfachmann/-frau",
  "Barkeeper",
  "Hotelmanager/in",
  "Reisekaufmann/-frau",
  "Tourismus-Manager/in",
  "Rezeptionist/in",
  "Housekeeping Manager/in",

  // Medien & Kreativ
  "Journalist/in",
  "Redakteur/in",
  "Fotograf/in",
  "Videograf/in",
  "Kameramann/-frau",
  "Cutter/in",
  "Regisseur/in",
  "Produzent/in",
  "Übersetzer/in",
  "Dolmetscher/in",

  // Immobilien
  "Immobilienmakler/in",
  "Immobilienverwalter/in",
  "Facility Manager/in",
  "Hausverwalter/in",
  "Bauleiter/in",
  "Architekt/in",

  // Management & Führung
  "Geschäftsführer/in",
  "CEO",
  "COO",
  "Abteilungsleiter/in",
  "Bereichsleiter/in",
  "Teamleiter/in",
  "Standortleiter/in",

  // Sonstige
  "Berufseinsteiger/in",
  "Praktikant/in",
  "Werkstudent/in",
  "Trainee",
  "Freiberufler/in",
  "Quereinsteiger/in",
  "Student/in",
  "Absolvent/in",
];

export const BRANCHEN: string[] = [
  "Informationstechnologie (IT)",
  "Software & Webentwicklung",
  "E-Commerce & Online-Handel",
  "Telekommunikation",
  "Finanzdienstleistungen & Banking",
  "Versicherungen",
  "Unternehmensberatung & Consulting",
  "Wirtschaftsprüfung & Steuerberatung",
  "Marketing & Werbung",
  "Medien & Verlagswesen",
  "Automobilindustrie",
  "Maschinenbau",
  "Elektrotechnik & Elektronik",
  "Chemie & Pharma",
  "Biotechnologie",
  "Medizintechnik",
  "Gesundheitswesen & Kliniken",
  "Pflege & Sozialwesen",
  "Bildung & Forschung",
  "Öffentlicher Dienst & Verwaltung",
  "Logistik & Transport",
  "Handel & Einzelhandel",
  "Großhandel & Distribution",
  "Bauwesen & Architektur",
  "Immobilienwirtschaft",
  "Energie & Umwelt",
  "Erneuerbare Energien",
  "Lebensmittelindustrie",
  "Gastronomie & Hotellerie",
  "Tourismus & Reisen",
  "Mode & Textil",
  "Luft- und Raumfahrt",
  "Rüstung & Verteidigung",
  "Landwirtschaft",
  "Handwerk",
  "Recht & Rechtsberatung",
  "Personalberatung & Recruiting",
  "Eventmanagement",
  "Sport & Fitness",
  "Kultur & Kunst",
  "Non-Profit / NGO",
  "Startups & Venture Capital",
  "Halbleiter & Chipindustrie",
  "Gaming & Unterhaltung",
  "Verpackungsindustrie",
  "Metallindustrie",
  "Holz- und Möbelindustrie",
  "Druckindustrie",
  "Sicherheitsdienste",
];

export const AUSBILDUNGEN: string[] = [
  // Schulabschlüsse
  "Pflichtschulabschluss",
  "Hauptschulabschluss",
  "Mittlere Reife / Realschulabschluss",
  "Fachabitur / Fachhochschulreife",
  "Abitur / Matura",
  "Berufsreifeprüfung (AT)",

  // Lehre / Ausbildung
  "Lehre / Berufsausbildung",
  "Lehrabschlussprüfung (AT)",
  "Duale Ausbildung",
  "Meisterprüfung",
  "Technikerausbildung",
  "Fachwirt/in",
  "Betriebswirt/in (IHK)",
  "Berufsakademie",

  // Akademisch
  "Bachelor of Arts (B.A.)",
  "Bachelor of Science (B.Sc.)",
  "Bachelor of Engineering (B.Eng.)",
  "Bachelor of Laws (LL.B.)",
  "Master of Arts (M.A.)",
  "Master of Science (M.Sc.)",
  "Master of Engineering (M.Eng.)",
  "Master of Laws (LL.M.)",
  "Master of Business Administration (MBA)",
  "Diplom (FH)",
  "Diplom (Uni)",
  "Magister",
  "Staatsexamen",
  "Doktorat / Promotion (Dr.)",
  "Habilitation (Prof.)",

  // Spezifisch AT/CH
  "HAK-Abschluss (AT)",
  "HTL-Abschluss (AT)",
  "HLW-Abschluss (AT)",
  "Kolleg (AT)",
  "Eidg. Fähigkeitszeugnis EFZ (CH)",
  "Eidg. Berufsattest EBA (CH)",
  "Höhere Fachschule HF (CH)",
  "Fachhochschule FH (CH)",

  // Sonstige
  "Weiterbildung / Zertifikat",
  "Kein formaler Abschluss",
  "In Ausbildung",
];

export const SPRACHEN: string[] = [
  "Deutsch (Muttersprache)",
  "Deutsch (C2 - Annähernd muttersprachlich)",
  "Deutsch (C1 - Fachkundige Kenntnisse)",
  "Deutsch (B2 - Selbstständige Sprachverwendung)",
  "Deutsch (B1 - Fortgeschrittene Kenntnisse)",
  "Deutsch (A2 - Grundlegende Kenntnisse)",
  "Deutsch (A1 - Anfänger)",
  "Englisch (Muttersprache)",
  "Englisch (C2 - Verhandlungssicher)",
  "Englisch (C1 - Fließend)",
  "Englisch (B2 - Gute Kenntnisse)",
  "Englisch (B1 - Fortgeschrittene Kenntnisse)",
  "Englisch (A2 - Grundkenntnisse)",
  "Französisch (Muttersprache)",
  "Französisch (C2 - Verhandlungssicher)",
  "Französisch (C1 - Fließend)",
  "Französisch (B2 - Gute Kenntnisse)",
  "Französisch (B1 - Fortgeschrittene Kenntnisse)",
  "Französisch (A2 - Grundkenntnisse)",
  "Italienisch (Muttersprache)",
  "Italienisch (C1 - Fließend)",
  "Italienisch (B2 - Gute Kenntnisse)",
  "Italienisch (B1 - Fortgeschrittene Kenntnisse)",
  "Spanisch (C1 - Fließend)",
  "Spanisch (B2 - Gute Kenntnisse)",
  "Spanisch (B1 - Fortgeschrittene Kenntnisse)",
  "Türkisch (Muttersprache)",
  "Türkisch (C1 - Fließend)",
  "Türkisch (B2 - Gute Kenntnisse)",
  "Serbisch (Muttersprache)",
  "Kroatisch (Muttersprache)",
  "Bosnisch (Muttersprache)",
  "Polnisch (Muttersprache)",
  "Rumänisch (Muttersprache)",
  "Ungarisch (Muttersprache)",
  "Tschechisch (Muttersprache)",
  "Slowakisch (Muttersprache)",
  "Russisch (Muttersprache)",
  "Russisch (C1 - Fließend)",
  "Ukrainisch (Muttersprache)",
  "Arabisch (Muttersprache)",
  "Arabisch (C1 - Fließend)",
  "Persisch/Farsi (Muttersprache)",
  "Portugiesisch (Muttersprache)",
  "Portugiesisch (B2 - Gute Kenntnisse)",
  "Chinesisch/Mandarin (Muttersprache)",
  "Chinesisch/Mandarin (B2 - Gute Kenntnisse)",
  "Japanisch (B2 - Gute Kenntnisse)",
  "Koreanisch (Muttersprache)",
  "Hindi (Muttersprache)",
  "Niederländisch (Muttersprache)",
  "Niederländisch (B2 - Gute Kenntnisse)",
  "Schwedisch (B2 - Gute Kenntnisse)",
  "Dänisch (B2 - Gute Kenntnisse)",
  "Norwegisch (B2 - Gute Kenntnisse)",
  "Griechisch (Muttersprache)",
  "Albanisch (Muttersprache)",
  "Bulgarisch (Muttersprache)",
  "Slowenisch (Muttersprache)",
  "Gebärdensprache (ÖGS/DGS)",
  "Latein (Latinum)",
];

export const LAENDER: string[] = [
  "Österreich",
  "Deutschland",
  "Schweiz",
];

export const BUNDESLAENDER_AT: string[] = [
  "Wien",
  "Niederösterreich",
  "Oberösterreich",
  "Salzburg",
  "Tirol",
  "Vorarlberg",
  "Steiermark",
  "Kärnten",
  "Burgenland",
];

export const BUNDESLAENDER_DE: string[] = [
  "Berlin",
  "Hamburg",
  "München / Bayern",
  "Nordrhein-Westfalen",
  "Baden-Württemberg",
  "Hessen",
  "Niedersachsen",
  "Sachsen",
  "Rheinland-Pfalz",
  "Schleswig-Holstein",
  "Brandenburg",
  "Thüringen",
  "Sachsen-Anhalt",
  "Mecklenburg-Vorpommern",
  "Bremen",
  "Saarland",
];

export const KANTONE_CH: string[] = [
  "Zürich",
  "Bern",
  "Basel",
  "Genf",
  "Luzern",
  "St. Gallen",
  "Aargau",
  "Waadt",
  "Tessin",
  "Wallis",
  "Freiburg",
  "Solothurn",
  "Thurgau",
  "Graubünden",
  "Schwyz",
  "Zug",
  "Neuenburg",
  "Schaffhausen",
];
